# Generated by Django 6.0.7 on 2026-07-24 14:49

from django.db import migrations


def copy_data(apps, schema_editor):
    """Copie les données de l'ancienne table oc_lettings_site.Profile vers profiles."""
    OldProfile = apps.get_model('oc_lettings_site', 'Profile')
    NewProfile = apps.get_model('profiles', 'Profile')

    for old in OldProfile.objects.all():
        NewProfile.objects.create(
            id=old.id,
            user_id=old.user_id,
            favorite_city=old.favorite_city,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('oc_lettings_site', '0002_related_name'),
    ]

    operations = [
        migrations.RunPython(copy_data),
    ]