# Generated by Django 6.0.7 on 2026-07-24 14:49

from django.db import migrations


def copy_data(apps, schema_editor):
    """Copie les données des anciennes tables oc_lettings_site vers lettings."""
    OldAddress = apps.get_model('oc_lettings_site', 'Address')
    NewAddress = apps.get_model('lettings', 'Address')
    OldLetting = apps.get_model('oc_lettings_site', 'Letting')
    NewLetting = apps.get_model('lettings', 'Letting')

    for old in OldAddress.objects.all():
        NewAddress.objects.create(
            id=old.id,
            number=old.number,
            street=old.street,
            city=old.city,
            state=old.state,
            zip_code=old.zip_code,
            country_iso_code=old.country_iso_code,
        )

    for old in OldLetting.objects.all():
        NewLetting.objects.create(
            id=old.id,
            title=old.title,
            address_id=old.address_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
        ('oc_lettings_site', '0002_related_name'),
    ]

    operations = [
        migrations.RunPython(copy_data),
    ]